# Site settings
title: Always Prototype
email: rise.shia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for today I learn. SW Development, ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://riseshia.github.io" # the base hostname & protocol for your site
twitter_username: Re_Shia
github_username:  riseshia

# Build settings
sass:
  style: compressed

markdown: kramdown
highlighter: pygments

paginate: 4

author: Shia

gems: [jekyll-paginate]

